##Software to install
Minimap2: /home/bep0022/bin/minimap2
TideHunter: /home/bep0022/miniconda3/bin/TideHunter
Porechop: /home/bep0022/repos/Porechop
samtools: /home/bep0022/miniconda3/bin/samtools
bedtools: /home/bep0022/miniconda3/bin/bedtools
seqkit: /home/bep0022/bin/seqkit
##References
#Must download
starts: telo_start_position_WT_2kb.txt
coverage: 2
ref: /hosted/biosc/SchwartzLab/ReferenceGenomes/Anolis/Anolis.sagrei.Bahama__Draft2021/AnoSag2.1_gene_annotation_032122_CDS.fa
outdir: /hosted/biosc/SchwartzLab/Nanopore/AnoleEmbryoOldiesTelomere/snakemake_out
reads: /hosted/biosc/SchwartzLab/Nanopore/AnoleEmbryoOldiesTelomere/BaseCalled_Guppy10_GPU_HAC_230622/pass/fastq_runid_d236a8400e4b3d9b7f03775a8afc182c26ff215e_1_0.fastq
telo_seq: TTAGGG
threads: 48
